# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Badge: https://github.com/Backlot-Cars/webapp/workflows/Continuous%20Integration/badge.sv

name: Release

on:
  pull_request:
   types: [opened, labeled, unlabeled, synchronize]
  pull_request:
    branches: [ master ]

jobs:
  check_label:
    name: Check pr label

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Running CI using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: NathanielHill/check-pr-label-action@v4.0.0
    with:
      github-token: '${{ secrets.GITHUB_TOKEN }}'
      valid-labels: 'minor, major, patch'